go.mod: bump Go toolchain version to v1.22.0
confidential-containers/trustee-operator pull request #57
Opened 2024-11-20 11:59 UTC by mythi

As of Go 1.21, toolchain versions must use the 1.N.P syntax.

Moreover, since Go 1.21 is no longer maintained, bump to Go 1.22 with the new syntax.

2024-11-25 17:13 UTC, lmilleri approved these changes
It looks good to me

2024-11-25 17:30 UTC, lmilleri requested changes
Please check if the new golang version is required in other places, eg:

.github/workflows/kuttl-int-tests.yaml
Dockerfile

2024-12-04 15:52 UTC, bpradipt approved these changes
/lgtm

2024-12-04 16:14 UTC, lmilleri approved these changes

2024-12-04 16:19 UTC, merged